<?php

// Set options on a new PHPMailer object so it sends email via Mailgun's servers.
function og_mailinglist_mailgun_og_mailinglist_new_phpmailer_alter(&$mailer) {
  // Check if a login/password is set for Mailgun.
  $login = variable_get('og_mailinglist_mailgun_login', '');
  $password = variable_get('og_mailinglist_mailgun_password','');
  if (empty($login) || empty($password)) {
    return;
  }
  else {
    $mailer->IsSMTP();
    $mailer->Mailer = "smtp";
    $mailer->Port = 587;
    $mailer->SMTPAuth = true; // turn on SMTP authentication
    $mailer->Username = $login; // SMTP username
    $mailer->Password = $password; // SMTP password
  }
}

/**
 * Implmentation of hook_menu().
 */
function og_mailinglist_mailgun_menu() {
  # Administration
  $items['admin/og/og_mailinglist/mailgun'] = array(
    'title' => 'OG Mailinglist Mailgun Settings',
    'description' => t('Manage Mailgun/OG Mailinglist integration settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('og_mailinglist_mailgun_admin_settings'),
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * Admin settings form
 */
function og_mailinglist_mailgun_admin_settings() {
  $form['og_mailinglist_mailgun_login'] = array(
    '#title' => t('Mailgun Login'),
    '#type' => 'textfield',
    '#default_value' => variable_get('og_mailinglist_mailgun_login', ''),
    '#description' => t('Mailgun Login. Find this by logging into Mailgun. Then clicking on "Domains". Then the domain you\'ll be using for sending OG Mailinglist emails.'),
  );
  $form['og_mailinglist_mailgun_password'] = array(
    '#title' => t('Mailgun Password'),
    '#type' => 'textfield',
    '#default_value' => variable_get('og_mailinglist_max_message_size', '100'),
    '#description' => t('Mailgun password. This can be found at the same place as the mailgun login.'),
  );

  return system_settings_form($form);
}
